export const questions_ch6 = [
  // CHƯƠNG 6 - BÀI 1: Tỉ lệ thức – Dãy tỉ số bằng nhau
  { id: "ch6_1_1", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Từ đẳng thức $ad = bc$ (với $a, b, c, d \\ne 0$), ta có thể suy ra tỉ lệ thức nào sau đây?", options: [{ id: "A", text: "$\\frac{a}{b} = \\frac{c}{d}$", isCorrect: true }, { id: "A", text: "$\\frac{a}{c} = \\frac{d}{b}$", isCorrect: false }, { id: "C", text: "$\\frac{d}{c} = \\frac{a}{b}$", isCorrect: false }, { id: "D", text: "$\\frac{a}{b} = \\frac{d}{c}$", isCorrect: false }] },
  { id: "ch6_1_2", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Tìm $x$ trong tỉ lệ thức $\\frac{x}{15} = \\frac{-4}{5}$", options: [{ id: "A", text: "$x = -12$", isCorrect: true }, { id: "B", text: "$x = 12$", isCorrect: false }, { id: "C", text: "$x = -3$", isCorrect: false }, { id: "D", text: "$x = 3$", isCorrect: false }] },
  { id: "ch6_1_3", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Cho dãy tỉ số bằng nhau $\\frac{x}{3} = \\frac{y}{4}$. Biết $x + y = 14$, tính $x, y$?", options: [{ id: "A", text: "$x = 6; y = 8$", isCorrect: true }, { id: "B", text: "$x = 8; y = 6$", isCorrect: false }, { id: "C", text: "$x = -6; y = -8$", isCorrect: false }, { id: "D", text: "$x = 3; y = 4$", isCorrect: false }] },
  { id: "ch6_1_4", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Cho $\\frac{x}{2} = \\frac{y}{5}$ và $y - x = 12$. Giá trị của $x$ là?", options: [{ id: "A", text: "$x = 8$", isCorrect: true }, { id: "B", text: "$x = 20$", isCorrect: false }, { id: "C", text: "$x = 4$", isCorrect: false }, { id: "D", text: "$x = 10$", isCorrect: false }] },
  { id: "ch6_1_5", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Tính chất nào sau đây của dãy tỉ số bằng nhau là ĐÚNG?", options: [{ id: "A", text: "$\\frac{a}{b} = \\frac{c}{d} = \\frac{a+c}{b+d}$", isCorrect: true }, { id: "B", text: "$\\frac{a}{b} = \\frac{c}{d} = \\frac{a\\cdot c}{b\\cdot d}$", isCorrect: false }, { id: "C", text: "$\\frac{a}{b} = \\frac{c}{d} = \\frac{a+c}{b-d}$", isCorrect: false }, { id: "D", text: "$\\frac{a}{b} = \\frac{c}{d} = \\frac{a-c}{b+d}$", isCorrect: false }] },
  { id: "ch6_1_6", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Thay tỉ số $1,5 : 2,5$ bằng tỉ số giữa các số nguyên ta được:", options: [{ id: "A", text: "$3 : 5$", isCorrect: true }, { id: "B", text: "$15 : 25$", isCorrect: false }, { id: "C", text: "$5 : 3$", isCorrect: false }, { id: "D", text: "$1 : 2$", isCorrect: false }] },
  { id: "ch6_1_7", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Một tam giác có chu vi 24cm và độ dài 3 cạnh tỉ lệ với 3; 4; 5. Cạnh lớn nhất của tam giác dài:", options: [{ id: "A", text: "10 cm", isCorrect: true }, { id: "B", text: "8 cm", isCorrect: false }, { id: "C", text: "12 cm", isCorrect: false }, { id: "D", text: "6 cm", isCorrect: false }] },
  { id: "ch6_1_8", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 45, question: "Cho $\\frac{x}{3} = \\frac{y}{2} = \\frac{z}{4}$ và $x + y - z = 5$. Tính $y$?", options: [{ id: "A", text: "$y = 10$", isCorrect: true }, { id: "B", text: "$y = 15$", isCorrect: false }, { id: "C", text: "$y = 5$", isCorrect: false }, { id: "D", text: "$y = 20$", isCorrect: false }] },
  { id: "ch6_1_9", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Tìm 2 số $x, y$ tỉ lệ với 5 và 7, biết $x + y = 36$?", options: [{ id: "A", text: "$x = 15; y = 21$", isCorrect: true }, { id: "B", text: "$x = 21; y = 15$", isCorrect: false }, { id: "C", text: "$x = 10; y = 26$", isCorrect: false }, { id: "D", text: "$x = 20; y = 16$", isCorrect: false }] },
  { id: "ch6_1_10", category: "Chương 6 - Bài 1", image: "/images/math7.png", timeLimit: 30, question: "Tỉ số của hai số là $\\frac{3}{5}$. Tổng của chúng là -32. Số bé là:", options: [{ id: "A", text: "-20$", isCorrect: true }, { id: "B", text: "-12$", isCorrect: false }, { id: "C", text: "12$", isCorrect: false }, { id: "D", text: "20$", isCorrect: false }] },

  // CHƯƠNG 6 - BÀI 2: Đại lượng tỉ lệ thuận
  { id: "ch6_2_1", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Đại lượng $y$ tỉ lệ thuận với đại lượng $x$ theo hệ số tỉ lệ $k$ thì:", options: [{ id: "A", text: "$y = kx$", isCorrect: true }, { id: "B", text: "$y = \\frac{k}{x}$", isCorrect: false }, { id: "C", text: "$xy = k$", isCorrect: false }, { id: "D", text: "$x = ky$", isCorrect: false }] },
  { id: "ch6_2_2", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Biết $y$ tỉ lệ thuận với $x$, và khi $x = 3$ thì $y = -6$. Hệ số tỉ lệ $k$ của $y$ đối với $x$ là:", options: [{ id: "A", text: "-2", isCorrect: true }, { id: "B", text: "2", isCorrect: false }, { id: "C", text: "$-\\frac{1}{2}$", isCorrect: false }, { id: "D", text: "$\\frac{1}{2}$", isCorrect: false }] },
  { id: "ch6_2_3", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Đại lượng $x$ tỉ lệ thuận với $y$ theo hệ số tỉ lệ $\\frac{1}{4}$. Khi $y = 8$ thì $x$ bằng:", options: [{ id: "A", text: "2", isCorrect: true }, { id: "B", text: "32", isCorrect: false }, { id: "C", text: "4", isCorrect: false }, { id: "D", text: "12", isCorrect: false }] },
  { id: "ch6_2_4", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Nếu $y$ tỉ lệ thuận với $x$ theo hệ số tỉ lệ là 5 thì $x$ tỉ lệ thuận với $y$ theo hệ số tỉ lệ là?", options: [{ id: "A", text: "$\\frac{1}{5}$", isCorrect: true }, { id: "B", text: "5", isCorrect: false }, { id: "C", text: "-5", isCorrect: false }, { id: "D", text: "$-\\frac{1}{5}$", isCorrect: false }] },
  { id: "ch6_2_5", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "10 lít dầu hỏa nặng 8kg. Hỏi 15 lít dầu hỏa nặng bao nhiêu kg?", options: [{ id: "A", text: "12 kg", isCorrect: true }, { id: "B", text: "10 kg", isCorrect: false }, { id: "C", text: "15 kg", isCorrect: false }, { id: "D", text: "9 kg", isCorrect: false }] },
  { id: "ch6_2_6", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Hai người cùng góp vốn kinh doanh với số tiền lần lượt là 20 triệu và 30 triệu. Số tiền lãi tỉ lệ thuận với vốn. Nếu tổng tiền lãi là 10 triệu, người ít vốn được chia bao nhiêu?", options: [{ id: "A", text: "4 triệu", isCorrect: true }, { id: "B", text: "6 triệu", isCorrect: false }, { id: "C", text: "5 triệu", isCorrect: false }, { id: "D", text: "3 triệu", isCorrect: false }] },
  { id: "ch6_2_7", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Chu vi của đường tròn $C = 2\\pi R$. Khẳng định nào ĐÚNG?", options: [{ id: "A", text: "$C$ tỉ lệ thuận với bán kính $R$", isCorrect: true }, { id: "B", text: "$C$ tỉ lệ nghịch với $R$", isCorrect: false }, { id: "C", text: "$C$ không tỉ lệ với $R$", isCorrect: false }, { id: "D", text: "$C$ tỉ lệ thuận với bình phương của $R$", isCorrect: false }] },
  { id: "ch6_2_8", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Chia số 104 thành 3 phần tỉ lệ thuận với 2; 3; 8. Phần nhỏ nhất là:", options: [{ id: "A", text: "16", isCorrect: true }, { id: "B", text: "24", isCorrect: false }, { id: "C", text: "64", isCorrect: false }, { id: "D", text: "14", isCorrect: false }] },
  { id: "ch6_2_9", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Học sinh 3 lớp 7A, 7B, 7C trồng đưọc số cây tỉ lệ với 3; 4; 5. Biết lớp 7A trồng ít hơn lớp 7B 5 cây. Số cây lớp 7C là:", options: [{ id: "A", text: "25 cây", isCorrect: true }, { id: "B", text: "20 cây", isCorrect: false }, { id: "C", text: "15 cây", isCorrect: false }, { id: "D", text: "10 cây", isCorrect: false }] },
  { id: "ch6_2_10", category: "Chương 6 - Bài 2", image: "/images/math7.png", timeLimit: 30, question: "Mối quan hệ giữa quãng đường $s$ và thời gian $t$ khi vận tốc $v$ không đổi là:", options: [{ id: "A", text: "Hai đại lượng tỉ lệ thuận", isCorrect: true }, { id: "B", text: "Hai đại lượng tỉ lệ nghịch", isCorrect: false }, { id: "C", text: "Không có quan hệ tỉ lệ", isCorrect: false }, { id: "D", text: "Tỉ lệ với bình phương thời gian $t$", isCorrect: false }] },

  // CHƯƠNG 6 - BÀI 3: Đại lượng tỉ lệ nghịch
  { id: "ch6_3_1", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Đại lượng $y$ tỉ lệ nghịch với đại lượng $x$ theo hệ số $a$ $(a \\ne 0)$ khi:", options: [{ id: "A", text: "$y = \\frac{a}{x}$", isCorrect: true }, { id: "B", text: "$y = ax$", isCorrect: false }, { id: "C", text: "$y = a + x$", isCorrect: false }, { id: "D", text: "$x = ay$", isCorrect: false }] },
  { id: "ch6_3_2", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Biết $x, y$ là hai đại lượng tỉ lệ nghịch. Khi $x = 4$ thì $y = -3$. Hệ số tỉ lệ $a$ là:", options: [{ id: "A", text: "-12", isCorrect: true }, { id: "B", text: "12", isCorrect: false }, { id: "C", text: "$-\\frac{3}{4}$", isCorrect: false }, { id: "D", text: "$\\frac{4}{3}$", isCorrect: false }] },
  { id: "ch6_3_3", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "12 người thợ xây xong một bức tường trong 6 ngày. Hỏi muốn xây xong trong 4 ngày cần bao nhiêu thợ (năng suất như nhau)?", options: [{ id: "A", text: "18 người", isCorrect: true }, { id: "B", text: "24 người", isCorrect: false }, { id: "C", text: "8 người", isCorrect: false }, { id: "D", text: "15 người", isCorrect: false }] },
  { id: "ch6_3_4", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Một ô tô chạy từ A đến B với vận tốc 60km/h hết 2 giờ. Nếu chạy với vận tốc 40km/h thì hết mấy giờ?", options: [{ id: "A", text: "3 giờ", isCorrect: true }, { id: "B", text: "4 giờ", isCorrect: false }, { id: "C", text: "2.5 giờ", isCorrect: false }, { id: "D", text: "1.5 giờ", isCorrect: false }] },
  { id: "ch6_3_5", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Cho $x$ và $y$ tỉ lệ nghịch. Nếu $x$ tăng lên 3 lần thì $y$ sẽ:", options: [{ id: "A", text: "Giảm đi 3 lần", isCorrect: true }, { id: "B", text: "Tăng lên 3 lần", isCorrect: false }, { id: "C", text: "Không đổi", isCorrect: false }, { id: "D", text: "Giảm đi 9 lần", isCorrect: false }] },
  { id: "ch6_3_6", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Diện tích hình chữ nhật $S$ bằng không đổi. Chiều dài $a$ và chiều rộng $b$ là hai đại lượng:", options: [{ id: "A", text: "Tỉ lệ nghịch với nhau", isCorrect: true }, { id: "B", text: "Tỉ lệ thuận với nhau", isCorrect: false }, { id: "C", text: "Không có quan hệ tỉ lệ", isCorrect: false }, { id: "D", text: "Bằng nhau", isCorrect: false }] },
  { id: "ch6_3_7", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Chia số 135 thành 3 phần tỉ lệ nghịch với 2; 3; 4. Phần lớn nhất là:", options: [{ id: "A", text: "60", isCorrect: true }, { id: "B", text: "30", isCorrect: false }, { id: "C", text: "45", isCorrect: false }, { id: "D", text: "50", isCorrect: false }] },
  { id: "ch6_3_8", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 45, question: "Hai bánh răng ăn khớp với nhau, bánh thứ nhất có 24 răng quay 1 phút được 100 vòng. Bánh thứ hai có 30 răng quay 1 phút được bao nhiêu vòng?", options: [{ id: "A", text: "80 vòng", isCorrect: true }, { id: "B", text: "125 vòng", isCorrect: false }, { id: "C", text: "150 vòng", isCorrect: false }, { id: "D", text: "90 vòng", isCorrect: false }] },
  { id: "ch6_3_9", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Hai đại lượng $x$ và $y$ tỉ lệ nghịch. Khi $x_1 = 2$ thì $y_1 = 15$. Khi $x_2 = 6$ thì $y_2$ bằng:", options: [{ id: "A", text: "5", isCorrect: true }, { id: "B", text: "10", isCorrect: false }, { id: "C", text: "45", isCorrect: false }, { id: "D", text: "30", isCorrect: false }] },
  { id: "ch6_3_10", category: "Chương 6 - Bài 3", image: "/images/math7.png", timeLimit: 30, question: "Một máy in tiêu thụ hết 1 hộp mực trong 15 giờ. Nếu đóng hộp lượng mực bằng $\\frac{3}{5}$ hộp ban đầu, máy sẽ chạy được bao lâu?", options: [{ id: "A", text: "9 giờ", isCorrect: true }, { id: "B", text: "25 giờ", isCorrect: false }, { id: "C", text: "12 giờ", isCorrect: false }, { id: "D", text: "10 giờ", isCorrect: false }] }
];
